POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1tZWlrYWxhIiwiaWQiOiI2NDAwOTRlMTBmZjYyMjc0NGZlNTBiMzUiLCJpYXQiOjE2NzgwMTU2MzYsImV4cCI6MTY3ODAxOTIzNn0.6W1XgCqp4L3hSmtWI4d41VqE3Os-_Sa9ENkX8t8TAt4

{
  "title": "Test 8",
  "author": "test",
  "url": "http://test",
  "likes": "2"
}